export const mockDocuments = [
  {
    id: 'doc-jan',
    display_name: 'Выписка_январь.csv',
    kind: 'csv',
    uploaded_at: '2024-02-12T08:45:00Z',
    status: 'готово',
  },
  {
    id: 'doc-feb',
    display_name: 'statement_february.xlsx',
    kind: 'excel',
    uploaded_at: '2024-02-20T13:10:00Z',
    status: 'анализируется',
  },
  {
    id: 'doc-mar',
    display_name: 'bank_march.pdf',
    kind: 'pdf',
    uploaded_at: '2024-03-02T09:30:00Z',
    status: 'готово',
  },
];

export const mockTransactions = [
  {
    id: 'tx-1',
    date: '2024-03-01',
    time: '09:12',
    document: 'bank_march.pdf',
    type: 'Поступление',
    category: 'Зарплата',
    counterparty: 'ООО «Ромашка»',
    inn: '7701234567',
    kpp: '770101001',
    purpose: 'Оплата услуг за февраль',
    amount: 240000,
    currency: 'RUB',
    balance: 540000,
    status: 'Выполнено',
    channel: 'API',
    tag: 'Рутинное',
  },
  {
    id: 'tx-2',
    date: '2024-03-01',
    time: '11:05',
    document: 'bank_march.pdf',
    type: 'Списание',
    category: 'Налоги',
    counterparty: 'ФНС России',
    inn: '7700000000',
    kpp: '770000000',
    purpose: 'НДС за 4 квартал',
    amount: -180000,
    currency: 'RUB',
    balance: 360000,
    status: 'Выполнено',
    channel: 'Интернет-банк',
    tag: 'Рутинное',
  },
  {
    id: 'tx-3',
    date: '2024-03-02',
    time: '10:47',
    document: 'bank_march.pdf',
    type: 'Списание',
    category: 'Подрядчики',
    counterparty: 'ООО «ДевСофт»',
    inn: '7722334455',
    kpp: '772201001',
    purpose: 'Аванс за разработку',
    amount: -320000,
    currency: 'RUB',
    balance: 40000,
    status: 'Ожидает',
    channel: 'API',
    tag: 'Требует внимания',
  },
  {
    id: 'tx-4',
    date: '2024-03-03',
    time: '16:32',
    document: 'bank_march.pdf',
    type: 'Поступление',
    category: 'Закупки',
    counterparty: 'ПАО «СтройМаркет»',
    inn: '7801239876',
    kpp: '780101001',
    purpose: 'Возврат депозита',
    amount: 125000,
    currency: 'RUB',
    balance: 165000,
    status: 'Выполнено',
    channel: 'Мобильный банк',
    tag: 'Рутинное',
  },
  {
    id: 'tx-5',
    date: '2024-03-04',
    time: '12:24',
    document: 'bank_march.pdf',
    type: 'Списание',
    category: 'Закупки',
    counterparty: 'ООО «Логистик»',
    inn: '7709876543',
    kpp: '770901001',
    purpose: 'Транспортные услуги',
    amount: -85000,
    currency: 'RUB',
    balance: 80000,
    status: 'Отклонено',
    channel: 'API',
    tag: 'Требует внимания',
  },
  {
    id: 'tx-6',
    date: '2024-03-05',
    time: '15:50',
    document: 'bank_march.pdf',
    type: 'Поступление',
    category: 'Прочее',
    counterparty: 'АО «Сити-Инвест»',
    inn: '7811223344',
    kpp: '781101001',
    purpose: 'Инвестиционный транш',
    amount: 420000,
    currency: 'RUB',
    balance: 500000,
    status: 'Выполнено',
    channel: 'API',
    tag: 'Высокий приоритет',
  },
];

export const mockAnalysis = {
  transactions: mockTransactions,
  activity_heatmap: [
    { day: '09:00', inflow: 120000, outflow: 45000 },
    { day: '11:00', inflow: 180000, outflow: 160000 },
    { day: '13:00', inflow: 95000, outflow: 40000 },
    { day: '15:00', inflow: 210000, outflow: 135000 },
    { day: '17:00', inflow: 60000, outflow: 85000 },
  ],
  cashflow: [
    { month: 'Январь', inFlow: 11.4, outFlow: 9.6 },
    { month: 'Февраль', inFlow: 12.8, outFlow: 10.2 },
    { month: 'Март', inFlow: 13.6, outFlow: 11.1 },
    { month: 'Апрель', inFlow: 12.9, outFlow: 10.4 },
  ],
  category_split: [
    { category: 'Зарплата', value: 4.8 },
    { category: 'Подрядчики', value: 3.6 },
    { category: 'Налоги', value: 2.4 },
    { category: 'Закупки', value: 1.8 },
    { category: 'Прочее', value: 1.3 },
  ],
  balance_projection: [
    { quarter: 'Q1', base: 12.5, stress: 11.2 },
    { quarter: 'Q2', base: 13.0, stress: 11.5 },
    { quarter: 'Q3', base: 13.4, stress: 11.8 },
    { quarter: 'Q4', base: 13.8, stress: 12.0 },
  ],
  counterparty_volume: [
    { name: 'ООО «ДевСофт»', value: 1520000 },
    { name: 'АО «Сити-Инвест»', value: 1210000 },
    { name: 'ООО «Ромашка»', value: 920000 },
    { name: 'ООО «Логистик»', value: 610000 },
  ],
  risk_mix: [
    { name: 'Низкий риск', value: 62 },
    { name: 'Средний риск', value: 28 },
    { name: 'Высокий риск', value: 10 },
  ],
  counterparty_trend: [
    { month: 'Ноя', operations: 78 },
    { month: 'Дек', operations: 92 },
    { month: 'Янв', operations: 110 },
    { month: 'Фев', operations: 128 },
    { month: 'Мар', operations: 138 },
  ],
  counterparty_velocity: [
    { week: 'Неделя 1', newPartners: 6, alerts: 1 },
    { week: 'Неделя 2', newPartners: 7, alerts: 2 },
    { week: 'Неделя 3', newPartners: 8, alerts: 2 },
    { week: 'Неделя 4', newPartners: 10, alerts: 3 },
  ],
  signals: [
    { title: 'Резкий рост оборотов', count: 3, provider: 'Отметка риск-мониторинга' },
    { title: 'Новый контрагент без истории', count: 2, provider: 'Внутренний скоринг' },
    { title: 'Повторные возвраты по одному ИНН', count: 1, provider: 'Фрод-модуль' },
  ],
  registry: [
    { name: 'ООО «ДевСофт»', inn: '7722334455', segment: 'IT сервисы', operations: 142, risk: 'средний' },
    { name: 'АО «Сити-Инвест»', inn: '7811223344', segment: 'Инвестиции', operations: 96, risk: 'низкий' },
    { name: 'ООО «Ромашка»', inn: '7701234567', segment: 'B2B услуги', operations: 88, risk: 'низкий' },
    { name: 'ООО «Логистик»', inn: '7709876543', segment: 'Логистика', operations: 74, risk: 'высокий' },
  ],
};

export function buildMockUpload(file) {
  const now = new Date();
  return {
    id: `doc-${now.getTime()}`,
    display_name: file.name,
    kind: file.name.split('.').pop(),
    uploaded_at: now.toISOString(),
    status: 'готово',
  };
}

export function mockExportCsv() {
  const headers = [
    'Дата',
    'Время',
    'Документ',
    'Тип',
    'Категория',
    'Контрагент',
    'ИНН',
    'КПП',
    'Назначение',
    'Сумма',
    'Валюта',
    'Статус',
    'Канал',
    'Тег',
  ];

  const rows = mockTransactions.map((tx) => [
    tx.date,
    tx.time,
    tx.document,
    tx.type,
    tx.category,
    tx.counterparty,
    tx.inn,
    tx.kpp,
    tx.purpose,
    tx.amount,
    tx.currency,
    tx.status,
    tx.channel,
    tx.tag,
  ]);

  return [headers, ...rows]
    .map((cells) => cells.map((cell) => `"${String(cell ?? '').replace(/\"/g, '""')}"`).join(';'))
    .join('\n');
}
